apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-config
    version: {{ .Chart.AppVersion }}

data:
  SPRING_DATASOURCE_URL: {{ .Values.backend.environment.SPRING_DATASOURCE_URL | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.global.environment | quote }}
  DATABASE_NAME: {{ .Values.mysql.environment.MYSQL_DATABASE | quote }}
  APPLICATION_CORS_ORIGINS: {{ .Values.backend.environment.APPLICATION_CORS_ORIGINS | quote}}
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.environment.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_APPLICATION_NAME: {{ .Chart.Name }}-backend
  ENVIRONMENT: {{ .Values.global.environment | quote }}

