apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-frontend
    version: {{ .Chart.AppVersion }}
    component: web

spec:
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend
        version: {{ .Chart.AppVersion }}
        component: web

    spec:
      serviceAccountName: {{ .Chart.Name }}-frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.containerPort }}
              name: http

          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}