apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-frontend
    version: {{ .Chart.AppVersion }}

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-frontend