apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.environment.MYSQL_ROOT_PASSWORD | b64enc }}