apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: chats # Unified namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: rupesh1997/chat-service-frontend:1.0.1
          ports:
            - containerPort: 8080 # ðŸ‘ˆ The port inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: chats # ðŸ‘ˆ Must match the Deployment namespace
spec:
  selector:
    app: chat-frontend
  ports:
    - protocol: TCP
      port: 4200       # ðŸ‘ˆ The port you use to call the service
      targetPort: 8080 # ðŸ‘ˆ Must match the containerPort above