spring:
  application:
    name: chat-service-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  datasource:
    url: jdbc:mysql://localhost:3306/chats
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #  thymeleaf:
  #    cache: false
  #    prefix: classpath:/templates/
  #    suffix: .html

  mvc:
    static-path-pattern: /uploads/**
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 10MB
        max-file-size: 10MB
        max-request-size: 10MB
  web:
    resources:
      static-locations: "file:./backend/uploads/"


server:
  port: 8181
  servlet:
    session:
      timeout: 1h

application:
  security:
    token:
      secret_key: ${SECRET_KEY:TSHKAHSHSGSTBNSGJKSWUYGWBJBTUHHSGDSGVDVSGHXWYTFGYUHJHCVXSHCFYGSDBSBVCHGSFCYTWGJBCNBVS}
      expiration: ${TOKEN_TIME_TO_LIVE_IN_SEC:1200}
  cors:
    allowed-origins: ${ALLOW_CORS_ORIGIN:http://localhost:3000,http://localhost:4200,http://192.168.1.70:3000}

logging:
  level:
    root: INFO
    com.alfarays: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

info:
  app:
    name: Chat Application Backend
    description: Professional one-to-one chat application
    version: 1.0.0
  developer:
    name: "Rupesh Dulal"
    email: "rupeshdulal672@gmail.com"

file:
  upload:
    directory: backend/uploads
